# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
GrapeVariety.create([{:wine_type => 'red', :name => "Abouriou"},
    {:wine_type => 'red', :name => "Acolon"},
    {:wine_type => 'red', :name => "Agiorgitiko"},
    {:wine_type => 'red', :name => "Aglianico"},
    {:wine_type => 'red', :name => "Aleatico"},
    {:wine_type => 'red', :name => "Alexandrouli"},
    {:wine_type => 'red', :name => "Alfrocheiro Preto"},
    {:wine_type => 'red', :name => "Alicante Bouschet"},
    {:wine_type => 'red', :name => "Alvarelhão"},
    {:wine_type => 'red', :name => "Brancelho"},
    {:wine_type => 'red', :name => "Ancellotta"},
    {:wine_type => 'red', :name => "Aragónez"},
    {:wine_type => 'red', :name => "Aramon"},
    {:wine_type => 'red', :name => "Aspiran"},
    {:wine_type => 'red', :name => "Aubun"},
    {:wine_type => 'red', :name => "Băbească Neagră"},
    {:wine_type => 'red', :name => "Baga"},
    {:wine_type => 'red', :name => "Barbarossa"},
    {:wine_type => 'red', :name => "Barbera"},
    {:wine_type => 'red', :name => "Bastardo"},
    {:wine_type => 'red', :name => "Trousseau"},
    {:wine_type => 'red', :name => "Black Muscat"},
    {:wine_type => 'red', :name => "Blatina"},
    {:wine_type => 'red', :name => "Blauburger"},
    {:wine_type => 'red', :name => "Blauer Portugieser"},
    {:wine_type => 'red', :name => "Kékoportó"},
    {:wine_type => 'red', :name => "Portugais"},
    {:wine_type => 'red', :name => "Blaufränkisch"},
    {:wine_type => 'red', :name => "Lemberger"},
    {:wine_type => 'red', :name => "Kékfrankos"},
    {:wine_type => 'red', :name => "Gamé"},
    {:wine_type => 'red', :name => "Bobal"},
    {:wine_type => 'red', :name => "Bogazkere"},
    {:wine_type => 'red', :name => "Bonarda"},
    {:wine_type => 'red', :name => "Bondola"},
    {:wine_type => 'red', :name => "Bovale Sardo"},
    {:wine_type => 'red', :name => "Borgonja Crna"},
    {:wine_type => 'red', :name => "Brachetto or Braquet"},
    {:wine_type => 'red', :name => "Bual"},
    {:wine_type => 'red', :name => "Boal"},
    {:wine_type => 'red', :name => "Cabernet Franc"},
    {:wine_type => 'red', :name => "Cabernet Sauvignon"},
    {:wine_type => 'red', :name => "Cabernet Severny"},
    {:wine_type => 'red', :name => "Caladoc"},
    {:wine_type => 'red', :name => "Calitor"},
    {:wine_type => 'red', :name => "Canaiolo"},
    {:wine_type => 'red', :name => "Carignan"},
    {:wine_type => 'red', :name => "Carignane"},
    {:wine_type => 'red', :name => "Cariñena"},
    {:wine_type => 'red', :name => "Carignano"},
    {:wine_type => 'red', :name => "Mazuelo"},
    {:wine_type => 'red', :name => "Carménère"},
    {:wine_type => 'red', :name => "Carnelian"},
    {:wine_type => 'red', :name => "Castelão"},
    {:wine_type => 'red', :name => "Periquita"},
    {:wine_type => 'red', :name => "Castiglione"},
    {:wine_type => 'red', :name => "Cesanese"},
    {:wine_type => 'red', :name => "Cesar"},
    {:wine_type => 'red', :name => "Charbono"},
    {:wine_type => 'red', :name => "Cienna"},
    {:wine_type => 'red', :name => "Ciliegiolo"},
    {:wine_type => 'red', :name => "Cinsaut"},
    {:wine_type => 'red', :name => "Cinsault"},
    {:wine_type => 'red', :name => "Ottavianello"},
    {:wine_type => 'red', :name => "Colorino"},
    {:wine_type => 'red', :name => "Complexa"},
    {:wine_type => 'red', :name => "Corvina"},
    {:wine_type => 'red', :name => "Corvinone"},
    {:wine_type => 'red', :name => "Counoise"},
    {:wine_type => 'red', :name => "Croatina"},
    {:wine_type => 'red', :name => "Darkenuša"},
    {:wine_type => 'red', :name => "Dobričić"},
    {:wine_type => 'red', :name => "Dolcetto"},
    {:wine_type => 'red', :name => "Domina"},
    {:wine_type => 'red', :name => "Dornfelder"},
    {:wine_type => 'red', :name => "Dunkelfelder"},
    {:wine_type => 'red', :name => "Duras"},
    {:wine_type => 'red', :name => "Durif"},
    {:wine_type => 'red', :name => "Petite Sirah"},
    {:wine_type => 'red', :name => "Espadeiro"},
    {:wine_type => 'red', :name => "Fer"},
    {:wine_type => 'red', :name => "Fetească Neagră"},
    {:wine_type => 'red', :name => "Frappato"},
    {:wine_type => 'red', :name => "Freisa"},
    {:wine_type => 'red', :name => "Frühroter Veltliner"},
    {:wine_type => 'red', :name => "Gaglioppo"},
    {:wine_type => 'red', :name => "Gamay"},
    {:wine_type => 'red', :name => "Gamay Noir"},
    {:wine_type => 'red', :name => "Garnatxa"},
    {:wine_type => 'red', :name => "Grenache"},
    {:wine_type => 'red', :name => "Garnacha"},
    {:wine_type => 'red', :name => "Cannonau"},
    {:wine_type => 'red', :name => "Garrut"},
    {:wine_type => 'red', :name => "Graciano"},
    {:wine_type => 'red', :name => "Moristel"},
    {:wine_type => 'red', :name => "Greco Nero"},
    {:wine_type => 'red', :name => "Grignolino"},
    {:wine_type => 'red', :name => "Gropello"},
    {:wine_type => 'red', :name => "Grolleau"},
    {:wine_type => 'red', :name => "Groslot"},
    {:wine_type => 'red', :name => "Helfensteiner"},
    {:wine_type => 'red', :name => "Heroldrebe"},
    {:wine_type => 'red', :name => "Hondarrabi Beltza"},
    {:wine_type => 'red', :name => "Jurancon noir"},
    {:wine_type => 'red', :name => "Kadarka"},
    {:wine_type => 'red', :name => "Kalecik Karasi"},
    {:wine_type => 'red', :name => "Kotsifali"},
    {:wine_type => 'red', :name => "Kratosija"},
    {:wine_type => 'red', :name => "Lagrein"},
    {:wine_type => 'red', :name => "Lambrusco"},
    {:wine_type => 'red', :name => "Limnio"},
    {:wine_type => 'red', :name => "Magarach Ruby"},
    {:wine_type => 'red', :name => "Magliocco"},
    {:wine_type => 'red', :name => "Malbec"},
    {:wine_type => 'red', :name => "Auxerrois"},
    {:wine_type => 'red', :name => "Cot"},
    {:wine_type => 'red', :name => "Malvasia di Schierano"},
    {:wine_type => 'red', :name => "Malvasia Nera"},
    {:wine_type => 'red', :name => "Mammolo"},
    {:wine_type => 'red', :name => "Mandelaria"},
    {:wine_type => 'red', :name => "Mandolari"},
    {:wine_type => 'red', :name => "Maratheftiko"},
    {:wine_type => 'red', :name => "Marsigliana"},
    {:wine_type => 'red', :name => "Marzemino"},
    {:wine_type => 'red', :name => "Mavro"},
    {:wine_type => 'red', :name => "Mavrodafni"},
    {:wine_type => 'red', :name => "Mavrodaphne"},
    {:wine_type => 'red', :name => "Mavrud"},
    {:wine_type => 'red', :name => "Mayorquin"},
    {:wine_type => 'red', :name => "Mencia"},
    {:wine_type => 'red', :name => "Jaen"},
    {:wine_type => 'red', :name => "Merlot"},
    {:wine_type => 'red', :name => "Millot"},
    {:wine_type => 'red', :name => "Mission"},
    {:wine_type => 'red', :name => "Molinara"},
    {:wine_type => 'red', :name => "Mondeuse"},
    {:wine_type => 'red', :name => "Monica"},
    {:wine_type => 'red', :name => "Montepulciano"},
    {:wine_type => 'red', :name => "Moreto"},
    {:wine_type => 'red', :name => "Mourisco Tinto"},
    {:wine_type => 'red', :name => "Mourvèdre"},
    {:wine_type => 'red', :name => "Monastrell"},
    {:wine_type => 'red', :name => "Mataro"},
    {:wine_type => 'red', :name => "Mujuretuli"},
    {:wine_type => 'red', :name => "Muscardin"},
    {:wine_type => 'red', :name => "Nebbiolo"},
    {:wine_type => 'red', :name => "Negoska"},
    {:wine_type => 'red', :name => "Négrette"},
    {:wine_type => 'red', :name => "Negroamaro"},
    {:wine_type => 'red', :name => "Negru de Dragasani"},
    {:wine_type => 'red', :name => "Nero d'Avola"},
    {:wine_type => 'red', :name => "Nerello Cappuccio"},
    {:wine_type => 'red', :name => "Nerello Mascalese"},
    {:wine_type => 'red', :name => "Nielluccio"},
    {:wine_type => 'red', :name => "Nocera"},
    {:wine_type => 'red', :name => "Nielluccio"},
    {:wine_type => 'red', :name => "Okuzgozu"},
    {:wine_type => 'red', :name => "Ojaleshi"},
    {:wine_type => 'red', :name => "Oseleta"},
    {:wine_type => 'red', :name => "Pais"},
    {:wine_type => 'red', :name => "Pamid"},
    {:wine_type => 'red', :name => "Perdal"},
    {:wine_type => 'red', :name => "Perricone"},
    {:wine_type => 'red', :name => "Petit Rouge"},
    {:wine_type => 'red', :name => "Petit Verdot"},
    {:wine_type => 'red', :name => "Piedirosso"},
    {:wine_type => 'red', :name => "Pignerol"},
    {:wine_type => 'red', :name => "Pignolo"},
    {:wine_type => 'red', :name => "Pineau d'Aunis"},
    {:wine_type => 'red', :name => "Pinot Meunier"},
    {:wine_type => 'red', :name => "Schwarzriesling"},
    {:wine_type => 'red', :name => "Müllerebe"},
    {:wine_type => 'red', :name => "Pinot Noir"},
    {:wine_type => 'red', :name => "Spätburgunder"},
    {:wine_type => 'red', :name => "Blauburgunder"},
    {:wine_type => 'red', :name => "Pinot Nero"},
    {:wine_type => 'red', :name => "Pinotage"},
    {:wine_type => 'red', :name => "Plavac Mali"},
    {:wine_type => 'red', :name => "Portan"},
    {:wine_type => 'red', :name => "Poulsard"},
    {:wine_type => 'red', :name => "Plousard"},
    {:wine_type => 'red', :name => "Prieto Picudo"},
    {:wine_type => 'red', :name => "Prokupac"},
    {:wine_type => 'red', :name => "Raboso"},
    {:wine_type => 'red', :name => "Ramisco"},
    {:wine_type => 'red', :name => "Refosco"},
    {:wine_type => 'red', :name => "Refošk"},
    {:wine_type => 'red', :name => "Roesler"},
    {:wine_type => 'red', :name => "Rondinella"},
    {:wine_type => 'red', :name => "Rossese"},
    {:wine_type => 'red', :name => "Rossola Nera"},
    {:wine_type => 'red', :name => "Rotberger"},
    {:wine_type => 'red', :name => "Rouchet"},
    {:wine_type => 'red', :name => "Ruché"},
    {:wine_type => 'red', :name => "Rubired"},
    {:wine_type => 'red', :name => "Ruby Cabernet"},
    {:wine_type => 'red', :name => "Rufete"},
    {:wine_type => 'red', :name => "Tinta Pinheira"},
    {:wine_type => 'red', :name => "Tinta Carvalha"},
    {:wine_type => 'red', :name => "Rufeta"},
    {:wine_type => 'red', :name => "Sagrantino"},
    {:wine_type => 'red', :name => "Sangiovese"},
    {:wine_type => 'red', :name => "Brunello"},
    {:wine_type => 'red', :name => "Saperavi"},
    {:wine_type => 'red', :name => "Schiava"},
    {:wine_type => 'red', :name => "Trollinger"},
    {:wine_type => 'red', :name => "Schioppettino"},
    {:wine_type => 'red', :name => "Schönburger"},
    {:wine_type => 'red', :name => "Sciacarello"},
    {:wine_type => 'red', :name => "Segalin"},
    {:wine_type => 'red', :name => "Shiraz"},
    {:wine_type => 'red', :name => "Syrah"},
    {:wine_type => 'red', :name => "Shiroka Melnishka Losa"},
    {:wine_type => 'red', :name => "Melnik"},
    {:wine_type => 'red', :name => "Sousão"},
    {:wine_type => 'red', :name => "St. Laurent"},
    {:wine_type => 'red', :name => "Taminga"},
    {:wine_type => 'red', :name => "Tannat"},
    {:wine_type => 'red', :name => "Tarrango"},
    {:wine_type => 'red', :name => "Tempranillo"},
    {:wine_type => 'red', :name => "Tinta Roriz"},
    {:wine_type => 'red', :name => "Ull de Llebre"},
    {:wine_type => 'red', :name => "Cencibel"},
    {:wine_type => 'red', :name => "Tinta del Pais"},
    {:wine_type => 'red', :name => "Teroldego"},
    {:wine_type => 'red', :name => "Terret Noir"},
    {:wine_type => 'red', :name => "Tibouren"},
    {:wine_type => 'red', :name => "Tinta Amarela"},
    {:wine_type => 'red', :name => "Tinta Barroca"},
    {:wine_type => 'red', :name => "Tinta Caiada"},
    {:wine_type => 'red', :name => "Tinta Francisca"},
    {:wine_type => 'red', :name => "Tinta Miuda"},
    {:wine_type => 'red', :name => "Tinta Negra Mole"},
    {:wine_type => 'red', :name => "Preto Martinho"},
    {:wine_type => 'red', :name => "Tinto Cão"},
    {:wine_type => 'red', :name => "Touriga Franca"},
    {:wine_type => 'red', :name => "Touriga Francesa"},
    {:wine_type => 'red', :name => "Touriga Nacional"},
    {:wine_type => 'red', :name => "Azal Espanhol"},
    {:wine_type => 'red', :name => "Preto de Mortágua"},
    {:wine_type => 'red', :name => "Trincadeira"},
    {:wine_type => 'red', :name => "Castelão"},
    {:wine_type => 'red', :name => "Torneiro"},
    {:wine_type => 'red', :name => "Troia"},
    {:wine_type => 'red', :name => "Uva di Troia"},
    {:wine_type => 'red', :name => "Trousseau"},
    {:wine_type => 'red', :name => "Uva Rara"},
    {:wine_type => 'red', :name => "Uva di Troia"},
    {:wine_type => 'red', :name => "Vaccarese"},
    {:wine_type => 'red', :name => "Valdiguié"},
    {:wine_type => 'red', :name => "Vespolina"},
    {:wine_type => 'red', :name => "Vranac"},
    {:wine_type => 'red', :name => "Wildbacher"},
    {:wine_type => 'red', :name => "Blauer Wildbacher"},
    {:wine_type => 'red', :name => "Xynomavro"},
    {:wine_type => 'red', :name => "Zinfandel"},
    {:wine_type => 'red', :name => "Crljenak Kaštelanski"},
    {:wine_type => 'red', :name => "Primitivo"},
    {:wine_type => 'red', :name => "Zweigelt"},
    {:wine_type => 'red', :name => "Zweigeltrebe"},
    {:wine_type => 'red', :name => "Rotburger"},
    {:wine_type => 'white', :name => "Aidani"},
    {:wine_type => 'white', :name => "Airén"},
    {:wine_type => 'white', :name => "Valdepeñas"},
    {:wine_type => 'white', :name => "Alarije"},
    {:wine_type => 'white', :name => "Albalonga"},
    {:wine_type => 'white', :name => "Albana"},
    {:wine_type => 'white', :name => "Albariño"},
    {:wine_type => 'white', :name => "Alvarinho"},
    {:wine_type => 'white', :name => "Cainho Branco"},
    {:wine_type => 'white', :name => "Albarola"},
    {:wine_type => 'white', :name => "Albillo"},
    {:wine_type => 'white', :name => "Aligoté"},
    {:wine_type => 'white', :name => "Altesse"},
    {:wine_type => 'white', :name => "Amigne"},
    {:wine_type => 'white', :name => "Ansonica"},
    {:wine_type => 'white', :name => "Antao Vaz"},
    {:wine_type => 'white', :name => "Arbois"},
    {:wine_type => 'white', :name => "Arinto"},
    {:wine_type => 'white', :name => "Arneis"},
    {:wine_type => 'white', :name => "Arnsburger"},
    {:wine_type => 'white', :name => "Arrufiac"},
    {:wine_type => 'white', :name => "Arvine"},
    {:wine_type => 'white', :name => "Assario branco"},
    {:wine_type => 'white', :name => "Assyrtiko"},
    {:wine_type => 'white', :name => "Athiri"},
    {:wine_type => 'white', :name => "Auxerrois Blanc"},
    {:wine_type => 'white', :name => "Avesso"},
    {:wine_type => 'white', :name => "Azal"},
    {:wine_type => 'white', :name => "Barcelo"},
    {:wine_type => 'white', :name => "Bacchus"},
    {:wine_type => 'white', :name => "Baiyu"},
    {:wine_type => 'white', :name => "Baroque"},
    {:wine_type => 'white', :name => "Biancone"},
    {:wine_type => 'white', :name => "Bical"},
    {:wine_type => 'white', :name => "Blanc de Morgex"},
    {:wine_type => 'white', :name => "Boais"},
    {:wine_type => 'white', :name => "Bogdanuša"},
    {:wine_type => 'white', :name => "Bombino Bianco"},
    {:wine_type => 'white', :name => "Borrado das Moscas"},
    {:wine_type => 'white', :name => "Bourboulenc"},
    {:wine_type => 'white', :name => "Bouvier"},
    {:wine_type => 'white', :name => "Breidecker"},
    {:wine_type => 'white', :name => "Bual"},
    {:wine_type => 'white', :name => "Bukettraube"},
    {:wine_type => 'white', :name => "Burger"},
    {:wine_type => 'white', :name => "Monbadon"},
    {:wine_type => 'white', :name => "Carignan blanc"},
    {:wine_type => 'white', :name => "Catarratto"},
    {:wine_type => 'white', :name => "Cayetana"},
    {:wine_type => 'white', :name => "Cereza"},
    {:wine_type => 'white', :name => "Chardonnay"},
    {:wine_type => 'white', :name => "Chasan"},
    {:wine_type => 'white', :name => "Chasselas"},
    {:wine_type => 'white', :name => "Fendant"},
    {:wine_type => 'white', :name => "Gutedel"},
    {:wine_type => 'white', :name => "Chenin Blanc"},
    {:wine_type => 'white', :name => "Pineau de la Loire"},
    {:wine_type => 'white', :name => "Steen"},
    {:wine_type => 'white', :name => "Clairette"},
    {:wine_type => 'white', :name => "Colombard"},
    {:wine_type => 'white', :name => "Completer"},
    {:wine_type => 'white', :name => "Cortese"},
    {:wine_type => 'white', :name => "Courbu"},
    {:wine_type => 'white', :name => "Xuri Zerratua"},
    {:wine_type => 'white', :name => "Bordelesa Zuri"},
    {:wine_type => 'white', :name => "Criolla Grande"},
    {:wine_type => 'white', :name => "Crouchen"},
    {:wine_type => 'white', :name => "Clare Riesling"},
    {:wine_type => 'white', :name => "Cape Riesling"},
    {:wine_type => 'white', :name => "Cygne blanc"},
    {:wine_type => 'white', :name => "Cserszegi Fűszeres"},
    {:wine_type => 'white', :name => "Debina"},
    {:wine_type => 'white', :name => "Diagalves"},
    {:wine_type => 'white', :name => "Dimiat"},
    {:wine_type => 'white', :name => "Dinka"},
    {:wine_type => 'white', :name => "Dona blanca"},
    {:wine_type => 'white', :name => "Doradillo"},
    {:wine_type => 'white', :name => "Drupeggio"},
    {:wine_type => 'white', :name => "Ehrenfelser"},
    {:wine_type => 'white', :name => "Elbling"},
    {:wine_type => 'white', :name => "Emerald Riesling"},
    {:wine_type => 'white', :name => "Emir Karasi"},
    {:wine_type => 'white', :name => "Encruzado"},
    {:wine_type => 'white', :name => "Erbaluce"},
    {:wine_type => 'white', :name => "Ezerjó"},
    {:wine_type => 'white', :name => "Faber"},
    {:wine_type => 'white', :name => "Faberrebe"},
    {:wine_type => 'white', :name => "Favorita"},
    {:wine_type => 'white', :name => "Falanghina"},
    {:wine_type => 'white', :name => "Fernao Pires"},
    {:wine_type => 'white', :name => "Ferral"},
    {:wine_type => 'white', :name => "Fetească Albă"},
    {:wine_type => 'white', :name => "Fetiaska"},
    {:wine_type => 'white', :name => "Leànyka"},
    {:wine_type => 'white', :name => "Fetească Regală"},
    {:wine_type => 'white', :name => "Fiano"},
    {:wine_type => 'white', :name => "Fie"},
    {:wine_type => 'white', :name => "Flora"},
    {:wine_type => 'white', :name => "Folle Blanche"},
    {:wine_type => 'white', :name => "Gros Plant"},
    {:wine_type => 'white', :name => "Piquepoult"},
    {:wine_type => 'white', :name => "Francusa"},
    {:wine_type => 'white', :name => "Freisamer"},
    {:wine_type => 'white', :name => "Friulano (ex Tocai Friulano)"},
    {:wine_type => 'white', :name => "Fromenteau"},
    {:wine_type => 'white', :name => "Frontignan"},
    {:wine_type => 'white', :name => "Furmint"},
    {:wine_type => 'white', :name => "Mosler"},
    {:wine_type => 'white', :name => "Sipon"},
    {:wine_type => 'white', :name => "Galego Dourado"},
    {:wine_type => 'white', :name => "Garganega Bianca"},
    {:wine_type => 'white', :name => "Garnacha blanca"},
    {:wine_type => 'white', :name => "Grenache Blanc"},
    {:wine_type => 'white', :name => "Gellewza"},
    {:wine_type => 'white', :name => "Gewürztraminer"},
    {:wine_type => 'white', :name => "Tramini"},
    {:wine_type => 'white', :name => "Gloria"},
    {:wine_type => 'white', :name => "Godello"},
    {:wine_type => 'white', :name => "Goldburger"},
    {:wine_type => 'white', :name => "Goldriesling"},
    {:wine_type => 'white', :name => "Gouais blanc"},
    {:wine_type => 'white', :name => "Grasă de Cotnari"},
    {:wine_type => 'white', :name => "Grecanico"},
    {:wine_type => 'white', :name => "Grechetto"},
    {:wine_type => 'white', :name => "Greco"},
    {:wine_type => 'white', :name => "Greco Bianco"},
    {:wine_type => 'white', :name => "Green Hungarian"},
    {:wine_type => 'white', :name => "Grenache Blanc"},
    {:wine_type => 'white', :name => "Garnacha blanca"},
    {:wine_type => 'white', :name => "Grenache Gris"},
    {:wine_type => 'white', :name => "Grignolino"},
    {:wine_type => 'white', :name => "Grillo"},
    {:wine_type => 'white', :name => "Grasa"},
    {:wine_type => 'white', :name => "Grk"},
    {:wine_type => 'white', :name => "Grolleau gris"},
    {:wine_type => 'white', :name => "Gros Manseng"},
    {:wine_type => 'white', :name => "Grüner Veltliner"},
    {:wine_type => 'white', :name => "Guardavalle"},
    {:wine_type => 'white', :name => "Guarnaccia Bianca"},
    {:wine_type => 'white', :name => "Gutenborner"},
    {:wine_type => 'white', :name => "Hárslevelű"},
    {:wine_type => 'white', :name => "Hondarribi Zuri"},
    {:wine_type => 'white', :name => "Humagne"},
    {:wine_type => 'white', :name => "Huxelrebe"},
    {:wine_type => 'white', :name => "Weisser Gutedel"},
    {:wine_type => 'white', :name => "Courtillier Musqué"},
    {:wine_type => 'white', :name => "Incrocio Manzoni"},
    {:wine_type => 'white', :name => "Inzolia"},
    {:wine_type => 'white', :name => "Irsai Oliver"},
    {:wine_type => 'white', :name => "Izsáki Sarfehér"},
    {:wine_type => 'white', :name => "Jacquère"},
    {:wine_type => 'white', :name => "Jaen blanca"},
    {:wine_type => 'white', :name => "Jampal"},
    {:wine_type => 'white', :name => "Juhfark"},
    {:wine_type => 'white', :name => "Keknyelu"},
    {:wine_type => 'white', :name => "Kerner"},
    {:wine_type => 'white', :name => "Knipperle"},
    {:wine_type => 'white', :name => "Klein Rauschling"},
    {:wine_type => 'white', :name => "Krstač"},
    {:wine_type => 'white', :name => "Kujundžuša"},
    {:wine_type => 'white', :name => "Ladikino"},
    {:wine_type => 'white', :name => "Len de l'El"},
    {:wine_type => 'white', :name => "Loureira"},
    {:wine_type => 'white', :name => "Macabeo"},
    {:wine_type => 'white', :name => "Macabeu"},
    {:wine_type => 'white', :name => "Alcañón"},
    {:wine_type => 'white', :name => "Viura"},
    {:wine_type => 'white', :name => "Madeleine Angevine"},
    {:wine_type => 'white', :name => "Malagousia"},
    {:wine_type => 'white', :name => "Malvar"},
    {:wine_type => 'white', :name => "Malvasia, includes several sub-varieties"},
    {:wine_type => 'white', :name => "Malvoisie"},
    {:wine_type => 'white', :name => "Mantonico Bianco"},
    {:wine_type => 'white', :name => "Petit Manseng"},
    {:wine_type => 'white', :name => "Izkiriota Ttipi"},
    {:wine_type => 'white', :name => "Gros Manseng"},
    {:wine_type => 'white', :name => "Izkiriota Handi"},
    {:wine_type => 'white', :name => "Manteudo"},
    {:wine_type => 'white', :name => "Maria Gomes"},
    {:wine_type => 'white', :name => "Fernão Pires"},
    {:wine_type => 'white', :name => "Marsanne"},
    {:wine_type => 'white', :name => "Mauzac"},
    {:wine_type => 'white', :name => "Melon de Bourgogne"},
    {:wine_type => 'white', :name => "Muscadet de Bourgogne"},
    {:wine_type => 'white', :name => "Merseguera"},
    {:wine_type => 'white', :name => "Escanyavella"},
    {:wine_type => 'white', :name => "Misket"},
    {:wine_type => 'white', :name => "Molette"},
    {:wine_type => 'white', :name => "Morio-Muskat"},
    {:wine_type => 'white', :name => "Moschofilero"},
    {:wine_type => 'white', :name => "Mtsvane"},
    {:wine_type => 'white', :name => "Müller-Thurgau"},
    {:wine_type => 'white', :name => "Rivaner"},
    {:wine_type => 'white', :name => "Muscadelle"},
    {:wine_type => 'white', :name => "Muscadet de Bourgogne"},
    {:wine_type => 'white', :name => "Melon de Bourgogne"},
    {:wine_type => 'white', :name => "Muscat"},
    {:wine_type => 'white', :name => "Moscato"},
    {:wine_type => 'white', :name => "Muscat of Alexandria"},
    {:wine_type => 'white', :name => "Moscatell"},
    {:wine_type => 'white', :name => "Moscatel de Málaga, de Setúbal"},
    {:wine_type => 'white', :name => "Muscat Blanc"},
    {:wine_type => 'white', :name => "Muscat Frontignan"},
    {:wine_type => 'white', :name => "Muskateller"},
    {:wine_type => 'white', :name => "Moscatel Branco"},
    {:wine_type => 'white', :name => "Muscadelle"},
    {:wine_type => 'white', :name => "Muscat Ottonel"},
    {:wine_type => 'white', :name => "Neuburger"},
    {:wine_type => 'white', :name => "Nosiola"},
    {:wine_type => 'white', :name => "Nuragus"},
    {:wine_type => 'white', :name => "Ondenc"},
    {:wine_type => 'white', :name => "Optima"},
    {:wine_type => 'white', :name => "Oremus"},
    {:wine_type => 'white', :name => "Ortega"},
    {:wine_type => 'white', :name => "Ortrugo"},
    {:wine_type => 'white', :name => "Oz"},
    {:wine_type => 'white', :name => "Parč"},
    {:wine_type => 'white', :name => "Palomino"},
    {:wine_type => 'white', :name => "Palomino Fino"},
    {:wine_type => 'white', :name => "Pardillo"},
    {:wine_type => 'white', :name => "Parellada"},
    {:wine_type => 'white', :name => "Pecorello"},
    {:wine_type => 'white', :name => "Pecorino"},
    {:wine_type => 'white', :name => "Perrum"},
    {:wine_type => 'white', :name => "Petite Arvine"},
    {:wine_type => 'white', :name => "Pedro Giménez"},
    {:wine_type => 'white', :name => "Pedro Ximénez"},
    {:wine_type => 'white', :name => "Alamís"},
    {:wine_type => 'white', :name => "Perle"},
    {:wine_type => 'white', :name => "Petit Courbu"},
    {:wine_type => 'white', :name => "Petit Meslier"},
    {:wine_type => 'white', :name => "Picolit"},
    {:wine_type => 'white', :name => "Picpoul"},
    {:wine_type => 'white', :name => "Pigato"},
    {:wine_type => 'white', :name => "Pinot Blanc"},
    {:wine_type => 'white', :name => "Pinot Bianco"},
    {:wine_type => 'white', :name => "Klevner"},
    {:wine_type => 'white', :name => "Weissburgunder"},
    {:wine_type => 'white', :name => "Pinot Grigio"},
    {:wine_type => 'white', :name => "Pinot Gris"},
    {:wine_type => 'white', :name => "Grauburgunder"},
    {:wine_type => 'white', :name => "Pinot Jaune"},
    {:wine_type => 'white', :name => "variant: Szürkebarát"},
    {:wine_type => 'white', :name => "Plavai"},
    {:wine_type => 'white', :name => "Pošip"},
    {:wine_type => 'white', :name => "Prosecco"},
    {:wine_type => 'white', :name => "Rabigato"},
    {:wine_type => 'white', :name => "Rabo de Ovelha"},
    {:wine_type => 'white', :name => "Rauschling"},
    {:wine_type => 'white', :name => "Regner"},
    {:wine_type => 'white', :name => "Reichensteiner"},
    {:wine_type => 'white', :name => "Rhoditis"},
    {:wine_type => 'white', :name => "Roditis"},
    {:wine_type => 'white', :name => "Ribolla"},
    {:wine_type => 'white', :name => "Robola"},
    {:wine_type => 'white', :name => "Riesling"},
    {:wine_type => 'white', :name => "Johannisberg Riesling"},
    {:wine_type => 'white', :name => "Rheinriesling"},
    {:wine_type => 'white', :name => "Klingelberger"},
    {:wine_type => 'white', :name => "Rieslaner"},
    {:wine_type => 'white', :name => "Rkatsiteli"},
    {:wine_type => 'white', :name => "Roditis"},
    {:wine_type => 'white', :name => "Rolle"},
    {:wine_type => 'white', :name => "Romorantin"},
    {:wine_type => 'white', :name => "Roter Veltliner"},
    {:wine_type => 'white', :name => "Rotgipfler"},
    {:wine_type => 'white', :name => "Roupeiro"},
    {:wine_type => 'white', :name => "Roussanne"},
    {:wine_type => 'white', :name => "Roussette"},
    {:wine_type => 'white', :name => "Sabro[1]"},
    {:wine_type => 'white', :name => "Sacy"},
    {:wine_type => 'white', :name => "Sarfeher"},
    {:wine_type => 'white', :name => "Sauvignon Blanc"},
    {:wine_type => 'white', :name => "variant: Sauvignon Gris"},
    {:wine_type => 'white', :name => "Sauvignon Vert, other name for Muscadelle"},
    {:wine_type => 'white', :name => "Savagnin"},
    {:wine_type => 'white', :name => "Savagnin Blanc"},
    {:wine_type => 'white', :name => "Traminer"},
    {:wine_type => 'white', :name => "Klevener de Heiligenstein"},
    {:wine_type => 'white', :name => "Savagnin Rosé"},
    {:wine_type => 'white', :name => "Savatiano"},
    {:wine_type => 'white', :name => "Scheurebe"},
    {:wine_type => 'white', :name => "Schönburger"},
    {:wine_type => 'white', :name => "Sémillon"},
    {:wine_type => 'white', :name => "Septiner"},
    {:wine_type => 'white', :name => "Sercial"},
    {:wine_type => 'white', :name => "Cerceal"},
    {:wine_type => 'white', :name => "Esgana Cao"},
    {:wine_type => 'white', :name => "Sereksia"},
    {:wine_type => 'white', :name => "Siegerrebe"},
    {:wine_type => 'white', :name => "Silvaner"},
    {:wine_type => 'white', :name => "Sylvaner"},
    {:wine_type => 'white', :name => "Österreicher"},
    {:wine_type => 'white', :name => "Smederevka"},
    {:wine_type => 'white', :name => "Spätrot"},
    {:wine_type => 'white', :name => "Zierfandler"},
    {:wine_type => 'white', :name => "Steen"},
    {:wine_type => 'white', :name => "Chenin Blanc"},
    {:wine_type => 'white', :name => "Sultana"},
    {:wine_type => 'white', :name => "Symphony"},
    {:wine_type => 'white', :name => "Tamarêz"},
    {:wine_type => 'white', :name => "Tamares"},
    {:wine_type => 'white', :name => "Crato Branco"},
    {:wine_type => 'white', :name => "Tamîioasa"},
    {:wine_type => 'white', :name => "Terrantez"},
    {:wine_type => 'white', :name => "Terret gris"},
    {:wine_type => 'white', :name => "Torrontés"},
    {:wine_type => 'white', :name => "Tourbat"},
    {:wine_type => 'white', :name => "Trebbiano"},
    {:wine_type => 'white', :name => "Ugni Blanc"},
    {:wine_type => 'white', :name => "Treixadura"},
    {:wine_type => 'white', :name => "Trajadura"},
    {:wine_type => 'white', :name => "Tresallier"},
    {:wine_type => 'white', :name => "Trousseau Gris"},
    {:wine_type => 'white', :name => "Grey Riesling"},
    {:wine_type => 'white', :name => "Verdelho"},
    {:wine_type => 'white', :name => "Gouveio"},
    {:wine_type => 'white', :name => "Godello"},
    {:wine_type => 'white', :name => "Verdiso"},
    {:wine_type => 'white', :name => "Verdia"},
    {:wine_type => 'white', :name => "Verdicchio"},
    {:wine_type => 'white', :name => "Verdejo"},
    {:wine_type => 'white', :name => "Verduzzo"},
    {:wine_type => 'white', :name => "Verduzzo Trevigiano"},
    {:wine_type => 'white', :name => "Vermentino"},
    {:wine_type => 'white', :name => "Rolle"},
    {:wine_type => 'white', :name => "Vernaccia"},
    {:wine_type => 'white', :name => "Vespaiola"},
    {:wine_type => 'white', :name => "Vilana"},
    {:wine_type => 'white', :name => "Vinhao"},
    {:wine_type => 'white', :name => "Viognier"},
    {:wine_type => 'white', :name => "Viosinho"},
    {:wine_type => 'white', :name => "Vitovska"},
    {:wine_type => 'white', :name => "Viura"},
    {:wine_type => 'white', :name => "Macabeo"},
    {:wine_type => 'white', :name => "Macabeu"},
    {:wine_type => 'white', :name => "Alcañón"},
    {:wine_type => 'white', :name => "Vugava"},
    {:wine_type => 'white', :name => "Welschriesling"},
    {:wine_type => 'white', :name => "Riesling Italico"},
    {:wine_type => 'white', :name => "Olaszrizling"},
    {:wine_type => 'white', :name => "Lazki Rizling"},
    {:wine_type => 'white', :name => "Graševina"},
    {:wine_type => 'white', :name => "Würzer"},
    {:wine_type => 'white', :name => "Xarel·lo"},
    {:wine_type => 'white', :name => "Xarello"},
    {:wine_type => 'white', :name => "Xynisteri"},
    {:wine_type => 'white', :name => "Zalema"},
    {:wine_type => 'white', :name => "Zéta"},
    {:wine_type => 'white', :name => "Zeusz"},
    {:wine_type => 'white', :name => "Zierfandler"},
    {:wine_type => 'white', :name => "Zilvaka"},
    {:wine_type => 'white', :name => "Žlahtina"}])